name: Build Sphinx Docs

on:
  pull_request:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: build docs
      uses: ./.github/workflows/docs-builder.yml
      with:
        artifact_name: sphinx-html
