name: Publish Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request: # temporary, remove before merge
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build docs
      uses: ./.github/workflows/docs-builder.yml
      with:
        artifact_name: sphinx-html

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: sphinx-html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: sphinx-html
