name: Publish Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request: # temporary, remove before merge
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies with Poetry
      run: |
        poetry install

    - name: Generate API documentation
      run: |
        poetry run sphinx-apidoc -o docs/apidocs biofefi

    - name: Build HTML documentation
      working-directory: docs
      run: make html

    - name: Upload artifacts (optional)
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: sphinx-html
        path: docs/_build/html

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: sphinx-html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: sphinx-html
