name: Run Unit Tests

on:
  - pull_request

jobs:
  run_unit_tests:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
       with:
         submodules: 'recursive'
         ref: ${{ github.ref }}
     - name: Install poetry
       run: pipx install poetry
     - name: Setup Python
       uses: actions/setup-python@v5.3.0
       with:
         python-version: '3.11'
         cache: "poetry"     
     - name: Install dependencies
       run: poetry install
     - name: Run pytest
       run: poetry run pytest